# https://taskfile.dev

version: '3'
vars:
  GO_PACKAGES:
    sh: go list ./...
  TAG:
  # sh: git describe --tags --abbrev=0
tasks:
  test-release:
    desc: Tests release process without publishing
    cmds:
      - goreleaser --snapshot --rm-dist
  check-data:
    desc: Checks dictionary data for duplicate entries
    cmds:
      - aspell -d en_US --ignore-case -c data/adjective
      - aspell -d en_US --ignore-case -c data/noun
      - cat data/adjective | uniq -d
      - cat data/noun | uniq -d
